query JobAuthDetailsQuery($id: ID!) {
  jobAuthDetails(id: $id) {
    opening {
      job {
        description
        info {
          title
        }
        attachments {
          fileName
          uri
        }
      }
    }
    buyer {
      info {
        location {
          country
        }
        stats {
          totalAssignments
          feedbackCount
          score
          totalCharges {
            amount
          }
        }
        company {
          companyId
          profile {
            industry
          }
        }
      }
      workHistory {
        startDate
        endDate
        jobInfo {
          title
          id
          access
          ciphertext
        }
        contractorInfo {
          contractorName
          ciphertext
        }
        feedback {
          score
          comment
        }
        feedbackToClient {
          score
          comment
        }
      }
    }
  }
}
